name: Linters and Code Analysis

# If a pull-request is pushed then cancel all previously running jobs related
# to that pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  # push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13"
      - run: pip install --upgrade tox
      - name: Run commitizen (https://commitizen-tools.github.io/commitizen/)
        run: tox -e cz
      - name: Run config-check
        run: tox -e config-check
      - name: Check LF line endings
        run: |
          if git grep -I -l $'\r' -- . ':!vendor' ':!node_modules'; then
            echo "❌ CRLF line endings detected!"
            exit 1
          fi

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: "docs/.markdownlint.yml"
          globs: |
            *.md

# for later release
  # lint-js:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Get changed JS files
  #       id: changed-js-files
  #       uses: tj-actions/changed-files@v44
  #       with:
  #         files: |
  #           **/*.js
  #           **/*.mjs
  #           **/*.cjs

  #     - name: Set up Node.js
  #       if: steps.changed-js-files.outputs.any_changed == 'true'
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'npm'
  #         cache-dependency-path: '**/package-lock.json'

  #     - name: Install dependencies
  #       if: steps.changed-js-files.outputs.any_changed == 'true'
  #       run: |
  #         if [ -f "package-lock.json" ]; then
  #           npm ci
  #         elif [ -f "package.json" ]; then
  #           npm install
  #         fi

  #     - name: Lint JS with ESLint
  #       if: steps.changed-js-files.outputs.any_changed == 'true'
  #       run: npm run lint -- ${{ steps.changed-js-files.outputs.all_changed_files }}

  lint-php-files:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed PHP files
        id: changed-php-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.php

      - name: Set up PHP ${{ matrix.php-version }}
        if: steps.changed-php-files.outputs.any_changed == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Composer dependencies
        if: steps.changed-php-files.outputs.any_changed == 'true'
        uses: ramsey/composer-install@v2
        with:
          # Ignore zip for php-webdriver/webdriver
          composer-options: "--ignore-platform-reqs"

      - name: Update the composer.lock file
        if: steps.changed-php-files.outputs.any_changed == 'true'
        run: composer update

      - name: Validate composer.json and composer.lock
        if: steps.changed-php-files.outputs.any_changed == 'true'
        run: composer validate --strict

      # TODO: Enable this after resolving issues
      # - name: Cache coding-standard
      #   # Allow the previous check to fail but not abort
      #   if: always()
      #   uses: actions/cache@v4
      #   with:
      #     path: .phpcs-cache
      #     key: phpcs-cache

      - name: Lint PHP syntax
        if: steps.changed-php-files.outputs.any_changed == 'true'
        run: |
          echo "Checking PHP syntax for changed files..."
          for file in ${{ steps.changed-php-files.outputs.all_changed_files }}; do
            php -l "$file"
          done

      - name: PHP-CS-Fixer (dry-run for CI)
        if: steps.changed-php-files.outputs.any_changed == 'true'
        run: composer lint -- ${{ steps.changed-php-files.outputs.all_changed_files }}

      - name: PHP_CodeSniffer (phpcs)
        if: steps.changed-php-files.outputs.any_changed == 'true'
        run: composer cs -- ${{ steps.changed-php-files.outputs.all_changed_files }}

      # TODO: Enable this after resolving issues
      # - name: Check coding-standard
      #   # Allow the previous check to fail but not abort
      #   if: always()
      #   run: composer phpcs

  analyse-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.4"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed PHP files
        id: changed-php-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.php

      - name: Get changed config files
        id: changed-config-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            phpstan.neon
            phpstan.neon.dist
            composer.json
            composer.lock

      - name: Set up PHP ${{ matrix.php-version }}
        if: steps.changed-php-files.outputs.any_changed == 'true' || steps.changed-config-files.outputs.any_changed == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      #          extensions: mbstring, iconv, mysqli, zip, gd, bz2

      - name: Install Composer dependencies
        if: steps.changed-php-files.outputs.any_changed == 'true' || steps.changed-config-files.outputs.any_changed == 'true'
        uses: ramsey/composer-install@v2

      - name: Cache Composer dependencies
        if: steps.changed-php-files.outputs.any_changed == 'true' || steps.changed-config-files.outputs.any_changed == 'true'
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-composer-

      - name: Analyse changed files with PHPStan
        if: steps.changed-php-files.outputs.any_changed == 'true' && steps.changed-config-files.outputs.any_changed != 'true'
        run: composer stan -- ${{ steps.changed-php-files.outputs.all_changed_files }}

      - name: Analyse all files with PHPStan (config changed)
        if: steps.changed-config-files.outputs.any_changed == 'true'
        run: composer stan

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Composer dependencies
        # Allow the previous check to fail but not abort
        if: always()
        uses: ramsey/composer-install@v2
        with:
          # Ignore zip for php-webdriver/webdriver
          composer-options: "--ignore-platform-req=ext-zip"

      - name: Create main config.php for unit tests
        run: cp config/config.dist.php config/config.php

      - name: Create plugin config.php for unit tests
        run: |
          for source in $(find plugins -type f -name "*dist*"); do
            target=$(echo "${source}" | sed -e "s/.dist//")
            if ! [ -f "config/$(basename ${target})" ]; then
              cp --no-clobber "${source}" "config/$(basename ${target})"
              sudo chown www-data:www-data "config/$(basename ${target})"
            fi
            if ! [ -f ${target} ]; then
              ln -s "config/$(basename ${target})" "${target}"
            fi
          done

      - name: Run PHPUnit tests
        if: steps.changed-php-files.outputs.any_changed == 'true' || steps.changed-config-files.outputs.any_changed == 'true'
        run: composer phpunit
